#Dockerfile
#
# arrs-sqlite-utility
# Start with a lightweight base image
FROM alpine:latest
 
# Install SQLite and for ease of docker inspection add Bash (since Alpine only includes 'ash’), and nano for editing scripts, cron to schedule repeat runs, and cURL for Bash based Pushover Notification script to call from MY ACTUAL scripts
RUN apk update && apk upgrade && apk add sqlite && apk add --no-cache bash && apk add --no-cache nano && apk --no-cache && apk add --no-cache cron
 
# Set the default working directory
WORKDIR /db
 
# Set the default command to open SQLite (was CMD ["sqlite3”]) but I removed that and put in placeholder to keep open ?
#CMD ["sqlite3"]
#CMD ["tail", "-f", "/dev/null"]  # Keeps the container running
#ENTRYPOINT ["/scripts/test.sh Sonarr"]


# Start cron in foreground & keep container alive
CMD cron -f
