#Dockerfile
#
# arrs-sqlite-utility
# Start with a lightweight base image
FROM alpine:latest
 
# Install SQLite and for ease of docker inspection add Bash (since Alpine only includes 'ash’), and nano for editing scripts, cron to schedule repeat runs, and cURL for Bash based Pushover Notification script to call from MY ACTUAL scripts
#RUN apk update && apk upgrade && apk add sqlite && apk add --no-cache bash && apk add --no-cache nano && apk --no-cache && apk add --no-cache cron
RUN apk update && apk upgrade && apk add --no-cache sqlite bash nano curl
 
# Set the default working directory
WORKDIR /db
 
# Set the default command to open SQLite (was CMD ["sqlite3”]) but I removed that and put in placeholder to keep open ?
#CMD ["sqlite3"]
#CMD ["tail", "-f", "/dev/null"]  # Keeps the container running
#ENTRYPOINT ["/scripts/test.sh Sonarr"]


# Copy script and cron job
# COPY container_cronjob /var/spool/cron/crontabs/container_cronjob
COPY log_message.sh /log_message.sh
#RUN echo '*/5 * * * *    /scripts/test.sh' > /etc/crontabs/root  # Don't use as this will wipe out the current periodic cron jobs in alpine image
#RUN echo '*       *       *       *       *       echo "From cron-Hello-NEW"' >> /etc/crontabs/root   #for testing run every 5 min (the pseudo crond required all in 1 file?
#RUN echo '38       */4       *       *       *       /scripts/arrs_log_check_dispatcher' >> /etc/crontabs/root        # *PROD* - Run every 4 hrs at 38 min past the hour
RUN echo '*       *       *       *       *       /scripts/arrs_log_check_dispatcher' >> /etc/crontabs/root           # ** -test- ** - Run every min for rapid testing (still needs to be named file with no .sh??)



# Set permissions
RUN chmod +x /log_message.sh
RUN chmod 0644 /var/spool/cron/crontabs/container_cronjob

# Start cron in foreground & keep container alive
# CMD cron -f -l 2
cmd cron -fbS -l 2 -d 0 -L /var/log/cron.log
